import { betterAuth } from 'better-auth';
import { prismaAdapter } from 'better-auth/adapters/prisma';
import { organization } from 'better-auth/plugins';
import type { AccessControl } from 'better-auth/plugins/access';
import { uuidv7 } from 'uuidv7';
import { PrismaClient } from '../generated/prisma';
import { loadRootEnv, envString } from '../common/env';
import { createSharedPrismaAdapter, registerPoolConsumer } from '../prisma/database';
import { ac as sharedAc, organizationRoles as sharedRoles } from '@kurultay/auth-access';

loadRootEnv();

const authSecret = process.env.BETTER_AUTH_SECRET?.trim();
if (!authSecret) {
  throw new Error('BETTER_AUTH_SECRET is required');
}

const prisma = new PrismaClient({ adapter: createSharedPrismaAdapter() });

// Better Auth's client borrows from the same pg pool as PrismaService. Hand its disconnect to
// the pool's owner (`prisma/database.ts`) instead of tearing it down from AuthModule: Nest
// does not order `onModuleDestroy` hooks, so a self-managed disconnect could land after the
// pool had already been ended. `closeSharedDatabase` now drains this client first, always.
registerPoolConsumer(() => prisma.$disconnect());

const betterAuthUrl = envString('BETTER_AUTH_URL', 'http://localhost:4000');
const webUrl = envString('WEB_URL', 'http://localhost:3000');

const ac = sharedAc;
const organizationRoles = sharedRoles;

export const auth = betterAuth({
  database: prismaAdapter(prisma, {
    provider: 'postgresql',
  }),
  secret: authSecret,
  baseURL: betterAuthUrl,
  basePath: '/auth',
  trustedOrigins: [webUrl],
  session: {
    // Avoids a database round trip on every authenticated request; the signed cookie
    // is re-validated against the DB once it expires.
    cookieCache: {
      enabled: true,
      maxAge: 5 * 60,
    },
  },
  advanced: {
    database: {
      generateId: () => uuidv7(),
    },
    // Cross-origin SPA (web :3000 → api :4000) needs SameSite=None in production HTTPS;
    // locally Better Auth defaults work with credentialed fetch on different ports.
    crossSubDomainCookies: {
      enabled: false,
    },
  },
  user: {
    modelName: 'user',
    fields: {
      image: 'avatarUrl',
    },
  },
  emailAndPassword: {
    enabled: true,
    requireEmailVerification: false,
  },
  plugins: [
    organization({
      // `createAccessControl` returns an access control narrowed to our own statements, which
      // is not assignable to the plugin's `AccessControl` parameter (its `newRole` is declared
      // over the open `Statements` type, so the two are contravariant). `roles` is deliberately
      // *not* cast: since better-auth 1.6 the plugin infers the invitation/member role union
      // from it, which is what makes `auth.api.createInvitation({ role })` reject anything
      // outside OWNER / ADMIN / MEMBER / GUEST.
      ac: ac as unknown as AccessControl,
      roles: organizationRoles,
      creatorRole: 'OWNER',
      // SECURITY — this `false` is what keeps GHSA-fmh4-wcc4-5jm3 (unauthorized invitation
      // acceptance via an unverified email match) reachable. Upgrading to better-auth 1.6
      // did *not* close it for us on its own.
      //
      // 1.6 hardened the default rather than the check: `accept-invitation` and
      // `get-invitation` now demand a verified email whenever the invitation id is not
      // generated by a built-in opaque generator, and our `advanced.database.generateId`
      // (uuidv7, above) counts as "not built-in". But that default only applies when this
      // option is left unset — set explicitly, it wins verbatim, so we stay opted out.
      //
      // Removing it is deliberately NOT done here: `requireEmailVerification` is false and
      // `sendInvitationEmail` below is a no-op, so no user can ever reach a verified state
      // and every invitation would become impossible to accept. Closing this properly means
      // shipping email delivery + verification first, then dropping this line. Until then
      // the residual exposure is an attacker who registers an unverified account on an
      // invited address before its real owner does, and holds the invitation id.
      requireEmailVerificationOnInvitation: false,
      async sendInvitationEmail() {
        // Email delivery is deferred beyond MVP; accept URL is returned by the API.
      },
      schema: {
        organization: {
          modelName: 'workspace',
        },
        member: {
          modelName: 'workspaceMember',
          fields: {
            organizationId: 'workspaceId',
          },
        },
        invitation: {
          modelName: 'workspaceInvitation',
          fields: {
            organizationId: 'workspaceId',
          },
        },
      },
    }),
  ],
});

export type AuthSession = typeof auth.$Infer.Session;
