import type { OrganizationOptions } from 'better-auth/plugins';
import type { AccessControl } from 'better-auth/plugins/access';
import { ac as sharedAc, organizationRoles as sharedRoles } from '@kurultay/auth-access';
import { buildInvitationEmail } from '../mail/mail-templates';
import { sendMail } from '../mail/send-mail';
import { evictUserFromWorkspaceSockets } from '../realtime/workspace-socket-eviction';
import { buildInviteAcceptUrl } from './web-urls';

/** The payload Better Auth hands to `sendInvitationEmail`, derived from the plugin's own type. */
type InvitationEmailData = Parameters<NonNullable<OrganizationOptions['sendInvitationEmail']>>[0];

/**
 * Options for the Better Auth organization plugin (our Workspace domain).
 *
 * Kept out of `auth.ts` so `organization-options.spec.ts` can assert on them without
 * importing `auth.ts`, which opens a Postgres pool at module load. The security setting
 * below is exactly the kind of line that gets "cleaned up" by someone who does not know what
 * it is holding closed, and a test is the only thing that notices.
 *
 * Deliberately **not** annotated with `OrganizationOptions`: since better-auth 1.6 the plugin
 * infers the invitation/member role union from `roles`, and that inference is what makes
 * `auth.api.createInvitation({ role })` reject anything outside OWNER / ADMIN / MEMBER /
 * GUEST. Widening this constant to the declared option type would throw that away.
 */
export const organizationOptions = {
  // `createAccessControl` returns an access control narrowed to our own statements, which is
  // not assignable to the plugin's `AccessControl` parameter (its `newRole` is declared over
  // the open `Statements` type, so the two are contravariant).
  ac: sharedAc as unknown as AccessControl,
  roles: sharedRoles,
  creatorRole: 'OWNER',
  // SECURITY (GHSA-fmh4-wcc4-5jm3) — an invitation may only be accepted, rejected or read by
  // a session whose email address is verified. Without it, whoever registers an unverified
  // account on an invited address first — the attacker, not necessarily its owner — can
  // accept the invitation and join the workspace.
  //
  // Better Auth 1.6 would already infer `true` here, because it turns the requirement on
  // whenever invitation ids are not generated by its own opaque generator and ours are
  // uuidv7 (`advanced.database.generateId` in `auth.ts`). That inference is not a safe thing
  // to depend on: it silently flips to `false` the day someone changes how ids are made.
  // Stating it is a decision about *our* product, and it stays independent of id generation.
  //
  // This is only reachable because email delivery exists now (`src/mail`): a user who is
  // never sent a verification link can never become verified, and every invitation would be
  // permanently unacceptable.
  requireEmailVerificationOnInvitation: true,
  async sendInvitationEmail(data: InvitationEmailData): Promise<void> {
    await sendMail(
      buildInvitationEmail({
        to: data.email,
        inviterName: data.inviter.user.name,
        workspaceName: data.organization.name,
        acceptUrl: buildInviteAcceptUrl(data.id),
      }),
    );
  },
  // HTTP membership revocation is immediate; Socket.io rooms are not. When Better Auth
  // removes a member — which is what `DELETE /workspaces/:workspaceId/members/:userId` does,
  // through `auth.api.removeMember` — drop their board and notification rooms so they stop
  // receiving tenant events.
  //
  // This covers removal only. `/organization/leave` deletes the membership without running
  // this hook, so `WorkspaceMemberService.leave` calls `evictUserFromWorkspaceSockets`
  // itself; the two paths must stay evenly covered.
  organizationHooks: {
    afterRemoveMember: async ({
      member,
      organization,
    }: {
      member: { userId: string };
      organization: { id: string };
    }) => {
      await evictUserFromWorkspaceSockets(organization.id, member.userId);
    },
  },
  schema: {
    organization: {
      modelName: 'workspace',
    },
    member: {
      modelName: 'workspaceMember',
      fields: {
        organizationId: 'workspaceId',
      },
    },
    invitation: {
      modelName: 'workspaceInvitation',
      fields: {
        organizationId: 'workspaceId',
      },
    },
  },
};
