import { execFileSync } from 'node:child_process';
import { mkdtemp, readFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { CursorPage, TaskDto, TrelloImportReportDto } from '@kurul/shared-types';
import { expect, test } from '../support/fixtures';
import { API_URL, WEB_URL } from '../stack-env';
import { machine, median, ms, p95, report, sorted } from './stats';

/**
 * The ROADMAP metric: *"a 500-card board imports in ≤2 minutes"*.
 *
 * Phase plan §4.1b is explicit that a duration without a machine and a method is not a result, and
 * that a number which cannot be measured is not to be claimed. So this file measures, prints, and
 * **asserts nothing about the duration** — `measure.config.ts` explains at length why a threshold
 * that fails a build gets raised until it stops meaning anything. What it does assert is that
 * every run was a genuine, complete import: a 201, a report, and — separately — 500 task rows read
 * back out of the database afterwards. A rig that timed a 413 and printed 40ms is the failure this
 * whole exercise exists to avoid.
 *
 * ## Three numbers, because "importing a board" is not one thing
 *
 * **Wall clock**, from the first byte of the POST leaving this process to the last byte of the
 * `201` arriving. That is the whole user-visible cost of the ROADMAP's sentence, and under
 * decision D5 (synchronous, no queue) it is also the whole server cost: there is nothing running
 * after the response.
 *
 * **Peak RSS of the API process**, sampled while the runs happen. The import buffers the body in
 * memory, `JSON.parse`s it, and builds a plan graph several times the size of the bytes — the
 * reason `TRELLO_IMPORT_MAX_BYTES` is a heap ceiling and not a disk one (`import-config.ts`). A
 * duration that is fine and a resident set that is not would still be a problem, and nothing else
 * in this repository looks at it.
 *
 * **Rows actually written**, counted through the API's own task listing rather than taken from the
 * import report. The report's counters come from the planner; counting them again from the other
 * side is what makes "500 cards were imported" a measurement instead of a restatement.
 *
 * ## What is deliberately NOT in any of these numbers
 *
 *  - **The reverse proxy.** These run against the suite's stack — a bare `node dist/main.js` on
 *    localhost — not the shipped Compose stack behind Caddy. Caddy buffers the request body and
 *    enforces `request_body { max_size 26MiB }`; neither cost appears here.
 *  - **The network.** Loopback only. A 1.4 MB body over a real uplink is bounded by bandwidth long
 *    before it is bounded by anything in this repository.
 *  - **Containers.** No cgroup CPU limit, no overlay filesystem: Postgres is in Docker, but the
 *    API process and the client are on the host, and no CPU or memory limit is applied to either.
 *  - **A cold anything.** The server is warm, the JIT is warm, Postgres's cache is warm, and the
 *    connection pool is already open. The first import after a boot is not represented.
 *  - **The rate limit.** The suite boots the API with `RATE_LIMIT_ENABLED=false`
 *    (`e2e/stack-env.ts`). In production `@ThrottleImport()` caps this endpoint at 3 per minute,
 *    so the five back-to-back runs below are not a shape a real client could produce.
 *  - **Concurrency.** One import at a time, one worker. Two people importing at once contend for
 *    the same connection pool and the same CPU, and that is not measured here.
 *
 * ## The fixture
 *
 * Generated by `scripts/generate-trello-fixture.mjs` into a temporary directory and deleted
 * afterwards — it is never committed (see that script's header for why, and for what it does not
 * measure). It is generated *here* rather than expected on disk so the measurement cannot silently
 * run against a stale file someone left in `/tmp` from a different seed.
 */

const RUNS = 5;

/** How often the API process's resident set is read. The peak below is the peak *of the samples*. */
const RSS_SAMPLE_MS = 100;

/**
 * Playwright transpiles these files to CommonJS, so `__dirname` is what resolves here — not
 * `import.meta.url`, which fails at load time with "Cannot use 'import.meta' outside a module".
 */
const GENERATOR = join(__dirname, '..', '..', 'scripts', 'generate-trello-fixture.mjs');

const FIXTURE_ARGS = [
  '--cards',
  '500',
  '--lists',
  '8',
  '--labels',
  '12',
  '--checklists-per-card',
  '2',
  '--items-per-checklist',
  '5',
  '--attachments-per-card',
  '1',
  '--seed',
  '20260815',
];

/**
 * The same bytes as an `ArrayBuffer`, which is what `File` accepts.
 *
 * Copied once, before any clock starts, rather than casting `Buffer`'s `ArrayBufferLike` away.
 */
function asArrayBuffer(bytes: Buffer): ArrayBuffer {
  const copy = new ArrayBuffer(bytes.byteLength);
  new Uint8Array(copy).set(bytes);
  return copy;
}

function tryCommand(command: string, args: string[]): string | null {
  try {
    return execFileSync(command, args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
  } catch {
    return null;
  }
}

/**
 * The pid of the API process Playwright booted, or `null` if it cannot be found.
 *
 * `null` is a supported outcome rather than a failure: the RSS number is a bonus, and a machine
 * without `lsof` or `pgrep` should still be able to take the duration measurement. What it must
 * not do is print a zero and let it be read as "the import used no memory" — hence the explicit
 * "not measured" line in the report below.
 */
function apiPid(): number | null {
  const port = new URL(API_URL).port;
  const candidates = [
    tryCommand('lsof', ['-ti', `tcp:${port}`, '-sTCP:LISTEN']),
    tryCommand('pgrep', ['-f', 'apps/api/dist/main.js']),
  ];
  for (const output of candidates) {
    const first = output?.trim().split('\n')[0];
    const pid = Number(first);
    if (Number.isInteger(pid) && pid > 0) return pid;
  }
  return null;
}

/** Resident set size of `pid` in bytes, via `ps`. Zero when it cannot be read. */
function rssBytes(pid: number): number {
  const output = tryCommand('ps', ['-o', 'rss=', '-p', String(pid)]);
  const kib = Number(output?.trim().split('\n')[0]);
  return Number.isFinite(kib) ? kib * 1024 : 0;
}

function mib(bytes: number): string {
  return `${(bytes / 1024 ** 2).toFixed(1)} MiB`;
}

test('500-card Trello import: wall clock, peak RSS, and the rows that landed', async ({
  stack,
}) => {
  const owner = await stack.createUser();
  const workspace = await stack.createWorkspace(owner);

  const dir = await mkdtemp(join(tmpdir(), 'kurul-trello-measure-'));
  const file = join(dir, 'trello-500.json');
  const generated = execFileSync('node', [GENERATOR, ...FIXTURE_ARGS, '--out', file], {
    encoding: 'utf8',
  }).trim();
  const bytes = await readFile(file);

  // Everything about the request a browser would send, including the `Origin` the API's origin
  // check requires on a multipart POST.
  const state = await owner.api.storageState();
  const cookie = state.cookies.map((entry) => `${entry.name}=${entry.value}`).join('; ');
  const url = `${API_URL}/workspaces/${workspace.id}/imports/trello`;

  const pid = apiPid();
  const baselineRss = pid === null ? 0 : rssBytes(pid);
  let peakRss = baselineRss;
  const sampler = setInterval(() => {
    if (pid !== null) peakRss = Math.max(peakRss, rssBytes(pid));
  }, RSS_SAMPLE_MS);

  const durations: number[] = [];
  const reports: TrelloImportReportDto[] = [];

  try {
    for (let run = 0; run < RUNS; run += 1) {
      const form = new FormData();
      // A fresh `File` per run over the same buffer: `FormData` holds a reference, and reusing one
      // instance would leave the second run measuring a consumed body.
      form.set(
        'file',
        new File([asArrayBuffer(bytes)], 'trello-500.json', { type: 'application/json' }),
      );

      const started = performance.now();
      const response = await fetch(url, {
        method: 'POST',
        headers: { cookie, origin: WEB_URL },
        body: form,
      });
      const body = await response.text();
      const elapsed = performance.now() - started;

      // The assertion that keeps the numbers meaning what they say. A 413, a 400 or a P2028 from
      // the transaction timeout all answer fast, and all three would otherwise be reported as an
      // excellent import time.
      expect(response.status, `run ${run + 1} was not accepted: ${body.slice(0, 400)}`).toBe(201);

      durations.push(elapsed);
      reports.push(JSON.parse(body) as TrelloImportReportDto);
    }
  } finally {
    clearInterval(sampler);
  }

  // ## The independent count
  //
  // Read back through `GET .../tasks`, page by page, rather than trusting the report. The report's
  // numbers come from the planner; these come from Postgres through a different query, which is
  // the only way "500 cards were imported" is a measurement rather than an echo.
  const last = reports[reports.length - 1]!;
  let counted = 0;
  let firstTaskId = '';
  let cursor: string | null = null;
  do {
    const page = await owner.api.get(
      `/workspaces/${workspace.id}/boards/${last.boardId}/tasks?limit=100` +
        (cursor === null ? '' : `&cursor=${cursor}`),
    );
    expect(page.ok(), `task page failed: ${page.status()}`).toBe(true);
    const body = (await page.json()) as CursorPage<TaskDto>;
    counted += body.items.length;
    if (firstTaskId === '') firstTaskId = body.items[0]?.id ?? '';
    cursor = body.nextCursor;
  } while (cursor !== null);

  expect(counted, 'the board must really hold 500 cards').toBe(500);
  expect(last.imported.tasks, 'the report must agree with the rows').toBe(counted);

  // The tasks are the headline number, but they are the *cheap* rows: 5000 checklist items are
  // most of what the transaction writes, and a count of tasks alone would be identical whether or
  // not any of them landed. One task read in full is enough to tell those two worlds apart.
  const detail = await owner.api.get(`/workspaces/${workspace.id}/tasks/${firstTaskId}`);
  expect(detail.ok(), `task detail failed: ${detail.status()}`).toBe(true);
  const task = (await detail.json()) as TaskDto;
  expect(task.checklists ?? []).toHaveLength(2);
  expect((task.checklists ?? []).flatMap((checklist) => checklist.items)).toHaveLength(10);

  await rm(dir, { recursive: true, force: true });

  report(`500-card Trello import (${RUNS} runs)`, [
    `machine      ${machine()}`,
    `stack        e2e stack: node ${API_URL} (no proxy, no container, no CPU limit), loopback;`,
    `             Postgres 18 in Docker on the same host`,
    `fixture      ${generated}`,
    `body         ${bytes.byteLength} bytes multipart (the JSON body limit is 1 MiB, which is why`,
    `             this endpoint takes multipart at all)`,
    `written/run  ${last.imported.columns} columns · ${last.imported.tasks} tasks · ` +
      `${last.imported.labels} labels · ${last.imported.checklists} checklists · ` +
      `${last.imported.checklistItems} checklist items · ${last.imported.attachments} links`,
    `verified     ${counted} task rows read back from the API after the last run`,
    `skippedTotal ${last.skipped.reduce((total, group) => total + group.count, 0)} across ` +
      `${last.skipped.length} (scope, reason) groups`,
    `duration     median ${ms(median(durations))} · p95 ${ms(p95(durations))}`,
    `raw (ms)     ${sorted(durations)
      .map((value) => value.toFixed(1))
      .join(' ')}`,
    pid === null
      ? `api rss      not measured (could not find the API process id on this machine)`
      : `api rss      baseline ${mib(baselineRss)} · peak ${mib(peakRss)} ` +
        `(sampled every ${RSS_SAMPLE_MS}ms, so this is the peak of the samples, not the peak)`,
    `budget       roadmap ≤120s · D5 re-opens the queue question above a 60s median ·`,
    `             the import transaction is capped at 180s (import-config.ts)`,
    `not measured reverse proxy · network · containers/CPU limits · cold start · rate limit ` +
      `(disabled) · concurrency`,
  ]);
});
